export { Header } from './Header/Header';
export { PersonalInfo } from './PersonalInfo/PersonalInfo';
export { Control } from './Control/Control';
export { Upload } from './Upload/Upload';
export { SectionTitle } from './SectionTitle/SectionTitle';
export { Card } from './Card/Card';
export { Education } from './Education/Education';
export { Experience } from './Experience/Experience';
export { Skills } from './Skills/Skills';
